DROP TABLE IF EXISTS TRANSACTION;



CREATE TABLE TRANSACTION (
  ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  AMOUNT DECIMAL(10,2) DEFAULT '0.00',
  TIMESTAMP BIGINT(20) UNSIGNED,
  CREATED_DATE TIMESTAMP NOT NULL,
  MODIFIED_DATE TIMESTAMP NOT NULL,
  PRIMARY KEY (ID)
);
